### ISSUE TITLE
Decoding/encoding not 1-to-1

### ISSUE THREAD

**Issue by yonatanzelnik** [sudo-vaibhav/emoji-uuid#1]
When I encode 'E' I get '😮‍'. But when I decode '😮‍', I get '' (empty string).

**Comment by sudo-vaibhav** [comment]
That's really strange. You can check the mapping in the mapping.ts file, there were problems before regarding duplicate emojis for two different characters but I guess I fixed that and this seems to be a different problem anyways. I'll try fixing it in a couple of days as I get time. Meanwhile any pull requests or insights would be appreciated! 😊

**Comment by sudo-vaibhav** [comment]
fixed by @Thakkar-Khushang and the latest version is out now on npm , please uninstall and reinstall @yonatanzelnik 😃
